// Code generated by MockGen. DO NOT EDIT.
// Source: interface_repository.go
//
// Generated by this command:
//
//	mockgen -package mocks -source interface_repository.go -destination ../mocks/mocks_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "newsportal/internal/authorization/entity"
	entity0 "newsportal/internal/like/entity"
	usecase "newsportal/internal/like/usecase"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionProvider is a mock of SessionProvider interface.
type MockSessionProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSessionProviderMockRecorder
	isgomock struct{}
}

// MockSessionProviderMockRecorder is the mock recorder for MockSessionProvider.
type MockSessionProviderMockRecorder struct {
	mock *MockSessionProvider
}

// NewMockSessionProvider creates a new mock instance.
func NewMockSessionProvider(ctrl *gomock.Controller) *MockSessionProvider {
	mock := &MockSessionProvider{ctrl: ctrl}
	mock.recorder = &MockSessionProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionProvider) EXPECT() *MockSessionProviderMockRecorder {
	return m.recorder
}

// Session mocks base method.
func (m *MockSessionProvider) Session(ctx context.Context, userID int) (*entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, userID)
	ret0, _ := ret[0].(*entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockSessionProviderMockRecorder) Session(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockSessionProvider)(nil).Session), ctx, userID)
}

// MockQueryRepository is a mock of QueryRepository interface.
type MockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockQueryRepositoryMockRecorder is the mock recorder for MockQueryRepository.
type MockQueryRepositoryMockRecorder struct {
	mock *MockQueryRepository
}

// NewMockQueryRepository creates a new mock instance.
func NewMockQueryRepository(ctrl *gomock.Controller) *MockQueryRepository {
	mock := &MockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepository) EXPECT() *MockQueryRepositoryMockRecorder {
	return m.recorder
}

// CountReaction mocks base method.
func (m *MockQueryRepository) CountReaction(ctx context.Context, request []usecase.CountRequest) ([]usecase.CountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReaction", ctx, request)
	ret0, _ := ret[0].([]usecase.CountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReaction indicates an expected call of CountReaction.
func (mr *MockQueryRepositoryMockRecorder) CountReaction(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReaction", reflect.TypeOf((*MockQueryRepository)(nil).CountReaction), ctx, request)
}

// MockCommandRepository is a mock of CommandRepository interface.
type MockCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockCommandRepositoryMockRecorder is the mock recorder for MockCommandRepository.
type MockCommandRepositoryMockRecorder struct {
	mock *MockCommandRepository
}

// NewMockCommandRepository creates a new mock instance.
func NewMockCommandRepository(ctrl *gomock.Controller) *MockCommandRepository {
	mock := &MockCommandRepository{ctrl: ctrl}
	mock.recorder = &MockCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRepository) EXPECT() *MockCommandRepositoryMockRecorder {
	return m.recorder
}

// ApplyReaction mocks base method.
func (m *MockCommandRepository) ApplyReaction(ctx context.Context, reaction entity0.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyReaction", ctx, reaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyReaction indicates an expected call of ApplyReaction.
func (mr *MockCommandRepositoryMockRecorder) ApplyReaction(ctx, reaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyReaction", reflect.TypeOf((*MockCommandRepository)(nil).ApplyReaction), ctx, reaction)
}

// IsReactionExist mocks base method.
func (m *MockCommandRepository) IsReactionExist(ctx context.Context, request *entity0.Reaction) (*entity0.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReactionExist", ctx, request)
	ret0, _ := ret[0].(*entity0.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReactionExist indicates an expected call of IsReactionExist.
func (mr *MockCommandRepositoryMockRecorder) IsReactionExist(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReactionExist", reflect.TypeOf((*MockCommandRepository)(nil).IsReactionExist), ctx, request)
}
